// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRKGHhszyz28z9B085FAE48k11uAoGC_g',
    appId: '1:405596786011:web:f6942de1bb46cb55845e7e',
    messagingSenderId: '405596786011',
    projectId: 'note-taking-app-9134f',
    authDomain: 'note-taking-app-9134f.firebaseapp.com',
    storageBucket: 'note-taking-app-9134f.firebasestorage.app',
    measurementId: 'G-CD7RQWWBVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRF1rAzon_yvXvh5ZDQ5UkYzOPWtHTJmk',
    appId: '1:405596786011:android:70c8bb52ad69a614845e7e',
    messagingSenderId: '405596786011',
    projectId: 'note-taking-app-9134f',
    storageBucket: 'note-taking-app-9134f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DsQbrljeqmQUV6hooOw6OCZ7kyYhJQc',
    appId: '1:405596786011:ios:0b1108ce996b6110845e7e',
    messagingSenderId: '405596786011',
    projectId: 'note-taking-app-9134f',
    storageBucket: 'note-taking-app-9134f.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DsQbrljeqmQUV6hooOw6OCZ7kyYhJQc',
    appId: '1:405596786011:ios:0b1108ce996b6110845e7e',
    messagingSenderId: '405596786011',
    projectId: 'note-taking-app-9134f',
    storageBucket: 'note-taking-app-9134f.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRKGHhszyz28z9B085FAE48k11uAoGC_g',
    appId: '1:405596786011:web:bbacee81fce062e7845e7e',
    messagingSenderId: '405596786011',
    projectId: 'note-taking-app-9134f',
    authDomain: 'note-taking-app-9134f.firebaseapp.com',
    storageBucket: 'note-taking-app-9134f.firebasestorage.app',
    measurementId: 'G-C20NZQYK8Z',
  );
}
